# Generated by Django 4.0.6 on 2022-08-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkey', models.PositiveSmallIntegerField()),
                ('fuel', models.CharField(choices=[('АИ-92', 'АИ-92'), ('АИ-95', 'АИ-95'), ('АИ-98', 'АИ-98'), ('ДТ', 'ДТ')], max_length=64)),
                ('price', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(max_length=64)),
            ],
        ),
    ]
