# Generated by Django 4.0.6 on 2022-08-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_othet', models.DateField()),
                ('volume_measurements', models.PositiveIntegerField()),
                ('counter', models.PositiveIntegerField()),
                ('strait', models.PositiveIntegerField()),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('surname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MoneySelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_othet', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('surname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(max_length=64)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.fuel')),
            ],
        ),
    ]
