# Generated by Django 4.0.6 on 2022-08-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('shop', '0001_initial'),
        ('office', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='shopkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.departments', to_field='internal_code'),
        ),
        migrations.AddField(
            model_name='moneyselling',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.paymenttype'),
        ),
        migrations.AddField(
            model_name='moneyselling',
            name='shopkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.departments', to_field='internal_code'),
        ),
        migrations.AddField(
            model_name='fuelselling',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.fuel'),
        ),
        migrations.AddField(
            model_name='fuelselling',
            name='shopkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.departments', to_field='internal_code'),
        ),
    ]
