# Generated by Django 4.0.6 on 2022-08-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ShopFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai92', models.BooleanField(default=True)),
                ('ai95', models.BooleanField(default=True)),
                ('ai98', models.BooleanField(default=True)),
                ('dt', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdano', models.BooleanField(default=True)),
                ('fuel_cards', models.BooleanField(default=True)),
                ('sber', models.BooleanField(default=True)),
                ('benzuber', models.BooleanField(default=True)),
                ('petrol', models.BooleanField(default=True)),
                ('e100', models.BooleanField(default=True)),
                ('fuelup', models.BooleanField(default=True)),
                ('vedomost', models.BooleanField(default=True)),
                ('lnr', models.BooleanField(default=True)),
                ('skidka', models.BooleanField(default=True)),
                ('rashod', models.BooleanField(default=True)),
            ],
        ),
    ]
