# Generated by Django 4.0.6 on 2022-08-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmoney',
            name='shopkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.departments', to_field='internal_code'),
        ),
        migrations.AddField(
            model_name='shopfuel',
            name='shopkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.departments', to_field='internal_code'),
        ),
    ]
